![](download.jpg)

In [5]:
dataset_1=[1,3,5]
dataset_2=[2,4,6]
import pandas as pd
series1= pd.Series(dataset_1)
series2= pd.Series(dataset_2)
S=series1 + series2
S

0     3
1     7
2    11
dtype: int64

In [53]:
Data1 = {"apple":[2], "orange":[5]}
import pandas as pd
package = pd.DataFrame(Data1)
package

apple  orange
0      2       5

In [45]:
import pandas as pd
purchase= pd.DataFrame(data, index= ["rob", "david", "haana"])
purchase

apple  orange
rob        2       5
david      2       5
haana      2       5

In [46]:
purchase.loc['david']

apple     2
orange    5
Name: david, dtype: int64

In [32]:
import pandas as pd
matches_df1 = pd.read_csv("example.csv")
matches_df1

Year       Institutional_sector_name  Institutional_sector_code  \
0      2008.03  Corporate business enterprises                        141   
1      2009.03  Corporate business enterprises                        141   
2      2010.03  Corporate business enterprises                        141   
3      2011.03  Corporate business enterprises                        141   
4      2012.03  Corporate business enterprises                        141   
...        ...                             ...                        ...   
18715  2013.03                   Pension funds                        261   
18716  2014.03                   Pension funds                        261   
18717  2015.03                   Pension funds                        261   
18718  2016.03                   Pension funds                        261   
18719  2017.03                   Pension funds                        261   

                                              Descriptor SNA08TRANS  \
0      Capital Account Opening balances Produced non-...    LS00000   
1      Capital Account Opening balances Produced non-...    LS00000   
2      Capital Account Opening balances Produced non-...    LS00000   
3      Capital Account Opening balances Produced non-...    LS00000   
4      Capital Account Opening balances Produced non-...    LS00000   
...                                                  ...        ...   
18715  Financial liabilities Closing balance Total fi...    LE00000   
18716  Financial liabilities Closing balance Total fi...    LE00000   
18717  Financial liabilities Closing balance Total fi...    LE00000   
18718  Financial liabilities Closing balance Total fi...    LE00000   
18719  Financial liabilities Closing balance Total fi...    LE00000   

      Asset_liability_code   Status  Values  
0                  AN10000  REVISED  225544  
1                  AN10000  REVISED  243315  
2                  AN10000  REVISED  259381  
3                  AN10000  REVISED  262596  
4                  AN10000  REVISED  267100  
...                    ...      ...     ...  
18715              AFL0000    FINAL   53768  
18716              AFL0000  REVISED   58559  
18717              AFL0000  REVISED   70099  
18718              AFL0000  REVISED   76021  
18719              AFL0000    FINAL   85190  

[18720 rows x 8 columns]

In [55]:
import numpy as np
a = np.array(42)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])



print(a.ndim)

print(b.ndim)

print(c.ndim)

print(d.ndim)

print (d)
print (type(a))

0
1
2
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
